export enum ChatMessageProtocol {
  CHAT_PLANE_KILL_SELF = 1,
  CHAT_PLANE_KILL_TEAM = 2,
  CHAT_PLANE_KILL_OPPONENT = 3,
  CHAT_MAN_KILL_SELF = 4,
  CHAT_MAN_KILL_TEAM = 5,
  CHAT_MAN_KILL_OPPONENT = 6,
  CHAT_CONTROL_END = 1,
  CHAT_CONTROL_START = 2,
  CHAT_KILL_TYPE_PLANE = 1,
  CHAT_KILL_TYPE_MAN = 2,
}